language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
# command to install dependencies
install:
  - pip install masonite-cli
  - craft install
script: python -m pytest

matrix:
  allow_failures:
    - python: 3.7-dev